// Generated by `npm run calibrate:jumps` from the local listening logs. Do not edit by hand.
// Trained on 208 Good / 212 Bad (closure+blended); held-out loop AUC 0.777, transition AUC 0.642.
import type { JumpModel } from './jumpModel'

export const TRAINED_JUMP_MODEL: JumpModel = {
  "version": "jump-logistic-v1",
  "features": [
    "closure",
    "blended"
  ],
  "mean": [
    0.3973921770386248,
    0.4523809523809524
  ],
  "std": [
    0.11298518156880039,
    0.49772726096111664
  ],
  "weights": [
    1.2432855554848206,
    1.0999457070279293
  ],
  "bias": -0.021161504923734
}
