/**
 * Fit P(Good) for a jump from the listening logs and write src/pack/trainedJumpModel.ts.
 * Every reported number is held out: loop wraps by song (the model never saw that song),
 * transitions by section pair (it never heard that pair, in either direction). Almost every
 * rated transition comes from one song, so transitions cannot yet be held out by song.
 * Run: npm run calibrate:jumps
 */
import fs from 'node:fs'
import { fitJumpModel, predictGood, type JumpModel } from '@/pack/jumpModel'
import type { JumpFeatureName } from '@/pack/jumpFeatures'
import { auc, loadRatedJumps, type RatedJump } from './jumpDataset.ts'

const LEVEL: JumpFeatureName[] = ['loudnessChangeDb', 'absLoudnessChangeDb']
const FEATURE_SETS: Record<string, JumpFeatureName[]> = {
  closure: ['closure'],
  'closure+blended': ['closure', 'blended'],
  split: ['closureIfCut', 'closureIfBlended', 'blended'],
  'split+level': ['closureIfCut', 'closureIfBlended', 'blended', ...LEVEL],
  'parts+split': ['seam', 'vibe', 'join', 'closureIfCut', 'closureIfBlended', 'blended'],
  'quality+blended': ['logQuality', 'blended'],
}
const VERSION = 'jump-logistic-v1'

type Held = RatedJump & { p: number }

/** Hold-out group for non-loop jumps: a section pair, or one exact simulator join. */
function pairOf(jump: RatedJump): string {
  if (jump.transition) return [jump.transition.fromLoop.key, jump.transition.toLoop.key].sort().join(' <> ')
  return jump.kind === 'pack' ? `${jump.song}|${jump.exitSec.toFixed(2)}|${jump.entrySec.toFixed(2)}` : ''
}

function heldOut(jumps: RatedJump[], features: JumpFeatureName[]): Held[] {
  const out: Held[] = []
  for (const song of new Set(jumps.map(j => j.song))) {
    const model = fitJumpModel(jumps.filter(j => j.song !== song), features, VERSION)
    for (const j of jumps.filter(j => j.song === song && j.kind === 'loop')) out.push({ ...j, p: predictGood(model, j.x) })
  }
  for (const pair of new Set(jumps.filter(j => j.kind !== 'loop').map(pairOf))) {
    const model = fitJumpModel(jumps.filter(j => pairOf(j) !== pair), features, VERSION)
    for (const j of jumps.filter(j => pairOf(j) === pair)) out.push({ ...j, p: predictGood(model, j.x) })
  }
  return out
}

function metrics(rows: Held[]) {
  const logLoss = (subset: Held[]) =>
    -subset.reduce((sum, r) => sum + Math.log(Math.max(1e-6, r.good ? r.p : 1 - r.p)), 0) / Math.max(1, subset.length)
  const a = (subset: Held[]) => auc(subset.map(r => ({ good: r.good, value: r.p })))
  const loops = rows.filter(r => r.kind === 'loop')
  const transitions = rows.filter(r => r.kind !== 'loop')
  // Agents choose among one song's jumps, so ranking within a song is what matters most.
  const perSong = [...new Set(loops.map(r => r.song))].map(song => a(loops.filter(r => r.song === song))).filter(v => !Number.isNaN(v))
  return {
    loopLogLoss: logLoss(loops), transitionLogLoss: logLoss(transitions),
    loopAuc: a(loops), loopWithinSong: perSong.reduce((s, v) => s + v, 0) / perSong.length,
    transitionAuc: a(transitions), combatToExploration: a(transitions.filter(r => r.direction === 'combat->exploration')),
  }
}

function reliability(label: string, rows: Held[]) {
  console.log(`  ${label}:`)
  for (const [lo, hi] of [[0, 0.3], [0.3, 0.5], [0.5, 0.7], [0.7, 1.01]] as const) {
    const bin = rows.filter(r => r.p >= lo && r.p < hi)
    const rate = bin.filter(r => r.good).length / Math.max(1, bin.length)
    console.log(`    predicted ${lo.toFixed(1)}-${Math.min(1, hi).toFixed(1)}: n=${String(bin.length).padStart(3)}, actually Good ${bin.length ? (rate * 100).toFixed(0) + '%' : '-'}`)
  }
}

function writeModel(model: JumpModel, summary: string) {
  fs.writeFileSync('src/pack/trainedJumpModel.ts', `// Generated by \`npm run calibrate:jumps\` from the local listening logs. Do not edit by hand.
// ${summary}
import type { JumpModel } from './jumpModel'

export const TRAINED_JUMP_MODEL: JumpModel = ${JSON.stringify(model, null, 2)}
`)
}

export async function main() {
  const { jumps } = loadRatedJumps()
  const count = (rows: RatedJump[]) => `${rows.filter(r => r.good).length} Good / ${rows.filter(r => !r.good).length} Bad`
  console.log(`Rated jumps: ${count(jumps)} (loop wraps ${count(jumps.filter(j => j.kind === 'loop'))},`
    + ` transitions ${count(jumps.filter(j => j.kind === 'transition'))}, simulator joins ${count(jumps.filter(j => j.kind === 'pack'))}; transitions over ${new Set(jumps.filter(j => j.transition).map(pairOf)).size} section pairs)`)
  console.log('\nHeld out (lower log loss is better; AUC 0.5 = chance):')
  const results = Object.entries(FEATURE_SETS).map(([name, features]) => {
    const rows = heldOut(jumps, features)
    const m = metrics(rows)
    console.log(`  ${name.padEnd(16)} loops: logLoss=${m.loopLogLoss.toFixed(3)} AUC=${m.loopAuc.toFixed(3)} within-song=${m.loopWithinSong.toFixed(3)}`
      + ` | transitions: logLoss=${m.transitionLogLoss.toFixed(3)} AUC=${m.transitionAuc.toFixed(3)} combat->exploration=${m.combatToExploration.toFixed(3)}`)
    return { name, features, rows, m }
  })
  const best = results.sort((a, b) => (a.m.loopLogLoss + a.m.transitionLogLoss) - (b.m.loopLogLoss + b.m.transitionLogLoss))[0]!
  console.log(`\nChosen: ${best.name} (lowest combined held-out log loss). Held-out reliability:`)
  reliability('loop wraps (cuts)', best.rows.filter(r => r.kind === 'loop'))
  reliability('transitions and simulator joins (mostly blended)', best.rows.filter(r => r.kind !== 'loop'))
  for (const threshold of [0.6, 0.7, 0.8]) {
    const kept = best.rows.filter(r => r.p >= threshold)
    console.log(`    p >= ${threshold}: keeps ${kept.filter(r => r.good).length} Good and ${kept.filter(r => !r.good).length} Bad`)
  }
  const model = fitJumpModel(jumps, best.features, VERSION)
  console.log('\nWeights on standardized features (all data):')
  best.features.forEach((name, i) => console.log(`  ${name.padEnd(20)} ${model.weights[i]! >= 0 ? '+' : ''}${model.weights[i]!.toFixed(3)}`))
  writeModel(model, `Trained on ${count(jumps)} (${best.name}); held-out loop AUC ${best.m.loopAuc.toFixed(3)},`
    + ` transition AUC ${best.m.transitionAuc.toFixed(3)}.`)
  console.log('Wrote src/pack/trainedJumpModel.ts')
}
